### PR TITLE
Implement get time difference for abbreviation

### PR DESCRIPTION
**Pull request by enzoh**

### CODE REVIEW

**Comment by klao** [comment]
Hi,

May I ask what are you using this function for? (Maybe there's a better solution for your use-case...)

**Comment by enzoh** [comment]
https://github.com/time-cube/time-cube/blob/master/src/Data/Time/Cube/Zone.hs#L268

**Comment by klao** [comment]
I see that it's needed to implement some type class. But, I don't see what is that type class is *useful for*. What is a reasonable use-case, where you only have an abbreviation in a time zone on your hands?..

Anyway, I added the function. (After rewriting it a bit and expanding the doc.)  Will push a new version in a moment.

I see that you are working actively on this time-cube thing, would you mind explaining very briefly what it is? And, if you have any other comments/requests/etc about `tz` I would be happy to hear them!

**Comment by klao** [comment]
Uploaded `0.0.0.10` to Hackage, should be available soon.

**Comment by enzoh** [comment]
Thanks, The class is needed to implement a generic timestamp parser [1]. The current design would support parsing format strings like "%Z", with no other information provided. I may need to revise this design. The time cube is a dependently-typed time library with efficient handling of leap seconds.

[1] https://github.com/time-cube/time-cube/blob/master/src/Data/Time/Cube/Parser.hs#L64

**Pull request closed without merging**
